### ISSUE TITLE
Add Persistence: Change database to Redis

### ISSUE THREAD

**Issue by jahnavik** [DevOps-Customers-J2MN/customers#39] opened 2018-04-06 19:09 UTC
**As a** Developer
**I need** to change the database to a persistent database 
**So that** the application survives a restart and avoids data loss, achieve resiliency

**Assumptions:**
* We will be using Redis database

**Acceptance Criteria:**
```
Given that a persistence model is added 
When the application shuts down or crashes
Then I can restart the application without losing data 
```

**Comment by nusrathbasheer91** [comment] 2018-04-10 22:58
Closing issue. Duplicate of issue #38

**Closed** 2018-04-10 23:00 UTC
Labels: duplicate, technical debt
